import joblib
from tkinter import *

def show_entry_fields():
    p1=int(e1.get())
    p2=int(e2.get())
    p3=int(e3.get())
    p4=int(e4.get())
    p5=int(e5.get())
    p6=int(e6.get())
    p7=int(e7.get())
    p8=int(e8.get())
    p9=int(e9.get())
    p10=int(e10.get())
    p11=int(e11.get())
    p12=int(e12.get())
    p13=int(e13.get())
    model=joblib.load('model_heart_diease')
    result=model.predict([[p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13]])

    if result==0:
        Label(master,text="No Heart Diseases").grid(row=31)
    else :
        Label(master,text="Possibility of Heart Diseases").grid(row=31)
master=Tk()
e1=StringVar()
e2=StringVar()
e3=StringVar()
e4=StringVar()
e5=StringVar()
e6=StringVar()
e7=StringVar()
e8=StringVar()
e9=StringVar()
e10=DoubleVar()
e11=StringVar()
e12=StringVar()
e13=StringVar()
master.title("Heart Disease Prediction System")
Label(master,text="Enter Your Age").grid(row=0)
Label(master,text="Male or Female [0/1]").grid(row=1)
Label(master,text="Enter Value of CP").grid(row=2)
Label(master,text="Enter Value of tresbps").grid(row=3)
Label(master,text="Enter Value of chol").grid(row=4)
Label(master,text="Enter Value of fbs").grid(row=5)
Label(master,text="Enter Value of restecg").grid(row=6)
Label(master,text="Enter Value of thalach").grid(row=7)
Label(master,text="Enter Value of exang").grid(row=8)
Label(master,text="Enter Value of oldpeak").grid(row=9)
Label(master,text="Enter Value of slope").grid(row=10)
Label(master,text="Enter Value of ca").grid(row=11)
Label(master,text="Enter Value of thal").grid(row=12)


re1=Entry(master,textvariable=e1).grid(row=0,column=1)
re2=Entry(master,textvariable=e2).grid(row=1,column=1)
re3=Entry(master,textvariable=e3).grid(row=2,column=1)
re4=Entry(master,textvariable=e4).grid(row=3,column=1)
re5=Entry(master,textvariable=e5).grid(row=4,column=1)
re6=Entry(master,textvariable=e6).grid(row=5,column=1)
re7=Entry(master,textvariable=e7).grid(row=6,column=1)
re8=Entry(master,textvariable=e8).grid(row=7,column=1)
re9=Entry(master,textvariable=e9).grid(row=8,column=1)
re10=Entry(master,textvariable=e10).grid(row=9,column=1)
re11=Entry(master,textvariable=e11).grid(row=10,column=1)
re12=Entry(master,textvariable=e12).grid(row=11,column=1)
re13=Entry(master,textvariable=e13).grid(row=12,column=1)

Button(master,text='Predict',command=show_entry_fields).grid()
mainloop()